# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_field',
        ),
    ]
